steps:
- name: "gcr.io/cloud-builders/docker"
  id: "Build the docker container"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/stats-pipeline:$_TAG", "."]

- name: "gcr.io/cloud-builders/docker"
  id: "Push the docker container to gcr.io"
  args: ["push", "gcr.io/$PROJECT_ID/stats-pipeline:$_TAG"]

- name: "gcr.io/cloud-builders/kubectl"
  id: "Create configmap manifest"
  entrypoint: /bin/bash
  args:
    - -c
    - |
      kubectl create configmap stats-pipeline-config \
      --from-file=k8s/data-processing/config/config.json -o yaml --dry-run > \
      configmap-manifest.json

- name: "gcr.io/cloud-builders/kubectl"
  id: "Apply configmap"
  args:
    - apply
    - -f
    - configmap-manifest.json
  env:
  - CLOUDSDK_COMPUTE_REGION=$_COMPUTE_REGION
  - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER

- name: "gcr.io/cloud-builders/gcloud"
  id: "Generate manifest for stats-pipeline deployment"
  entrypoint: /bin/sh
  args:
  - -c
  - |
    sed 's/{{GCLOUD_PROJECT}}/${PROJECT_ID}/g' \
    k8s/data-processing/deployments/stats-pipeline.yaml > \
    manifest.yaml

- name: "gcr.io/cloud-builders/gke-deploy"
  id: "Create stats-pipeline deployment"
  args:
  - run
  - --filename=manifest.yaml
  - --image=gcr.io/$PROJECT_ID/stats-pipeline:$_TAG
  - --location=$_COMPUTE_REGION
  - --cluster=$_CLUSTER

- name: "gcr.io/cloud-builders/kubectl"
  id: "Create stats-pipeline service"
  args:
    - apply
    - -f
    - k8s/data-processing/services/stats-pipeline.yaml
  env:
  - CLOUDSDK_COMPUTE_REGION=$_COMPUTE_REGION
  - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER

- name: "gcr.io/cloud-builders/docker"
  id: "Build the maptiles docker container"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/maptiles:$_TAG", "maptiles/"]

- name: "gcr.io/cloud-builders/docker"
  id: "Push the maptiles docker container to gcr.io"
  args: ["push", "gcr.io/$PROJECT_ID/maptiles:$_TAG"]

- name: "gcr.io/cloud-builders/gcloud"
  id: "Generate manifest for the maptiles "
  entrypoint: /bin/sh
  args:
  - -c
  - |
    sed 's/{{GCLOUD_PROJECT}}/${PROJECT_ID}/g' \
    k8s/data-processing/jobs/maptiles-runner.yaml > \
    maptiles-runner.yaml

- name: "gcr.io/cloud-builders/gke-deploy"
  id: "Create runner CronJob"
  args:
  - run
  - --filename=maptiles-runner.yaml
  - --image=gcr.io/$PROJECT_ID/maptiles:$_TAG
  - --location=$_COMPUTE_REGION
  - --cluster=$_CLUSTER
